### ISSUE TITLE
Support for HierarchicalContainer

### ISSUE THREAD

**Issue by mcooper7290** [vaadin/tree-grid#5]
Why does GridTree require its own GridTreeContainer instead of using HierarchicalContainer?  Most of our code already generates HierarchicalContainer so creating yet another container seems like a lot of extra work.

**Comment by wbadam** [comment]
You can use HierarchicalContainer, TreeGrid doesn't have it's own. You need to use one that implements the Indexed and Hierarchical interfaces and optionally the Collapsible interface. In case Hierarchical is not implemented, TreeGrid will use a wrapper so that the data can present hierarchy.
You may be mixing this official Vaadin add-on (TreeGrid) with the earlier experimental GridTree add-on that's also in the directory.
