### ISSUE TITLE
Select items that are collapsed

### ISSUE THREAD

**Issue by enkaradura** [vaadin/tree-grid#8]
It should be possible to select items that are not showing at the moment. My logic selects all the child items when a parent item is selects in multiselection mode.
The problem is that  containsId method in ContainerCollapsibleWrapper only searches for the id in the visible items but should search on all items of the container that are not filtered out.

   public boolean containsId(Object itemId) {
      return this.visibleItemIds.contains(itemId);
   }

**Comment by wbadam** [comment]
`containsId(Object itemId)` by specification should return the visible item ids, please refer to that in the `Container` interface.

For selection support, you can create your own container that implements all `Indexed`, `Hierarchical` and `Collapsible` and make `Hierarchical#getChildren()` return all visible and invisible items. Then collapse and expand items using a filter or other advanced method (instead of removing from the container as in the demo).

We are evaluating a possible support for child item selection but it is not trivial as lazy loading, non in memory containers and other factors need to be taken into account.
